### ISSUE TITLE
ARCH=i686 causes "library target names cannot contain hyphens" error

### ISSUE THREAD

**Issue by joshlf** [carllerche/travis-rust-matrix#4]
[This commit](https://github.com/ezrosent/allocators-rs/pull/135/commits/a8259ae71374bffffacceb758bf154c70e629fb8) (adding architectures to the `.travis.yml` file in one of my projects) causes [this error](https://travis-ci.org/ezrosent/allocators-rs/jobs/331385101#L548) on Travis:

```text
+cargo test --target i686-unknown-linux-gnu
error: failed to parse manifest at `/home/travis/build/ezrosent/allocators-rs/alloc-fmt/Cargo.toml`
Caused by:
  library target names cannot contain hyphens: alloc-fmt
```

This job is running with `ARCH=i686`. This error doesn't appear on `ARCH=x86_64` jobs.

**Comment by carllerche** [comment]
Thanks for the report. Did you figure out what causes the issue? I am unsure how the failure would relate to this repo :)

**Comment by joshlf** [comment]
I did not figure it out, no :(

**Comment by joshlf** [comment]
However, it looks like it's an issue with the version of cargo that is used when `ARCH=i686` - like it's a different version that for some reason doesn't support hyphens in crate names, while the version used with `ARCH=x86_64` does.

**Comment by carllerche** [comment]
That is what it looks like, but I am not sure what would cause that. Perhaps i686 was deprecated?

**Comment by joshlf** [comment]
Hmm I can't find anything about it being deprecated. But I also can't find anything about it not supporting hyphens. I'll ask around and maybe file an issue on the cargo repo.

**Comment by joshlf** [comment]
@carllerche @ehuss managed to track down the issue on the Cargo issue:

> I think the issue is that when the code in https://github.com/carllerche/travis-rust-matrix/blob/master/test sets up a cross compile it naively creates a new Cargo.toml with the `[lib]` name set to the name of the package. This isn't allowed, it must be underscores. I would say that shell script needs to be changed to change dashes to underscores on [this line](https://github.com/carllerche/travis-rust-matrix/blob/df450e9556b1d732399b8a56f396eec14d9d88bd/test#L94).

**Comment by carllerche** [comment]
Nice! Would you mind submitting a PR with the fix?

**Comment by joshlf** [comment]
Sure thing!
